In [2]:
import numpy as np 
import pandas as pd 

import os
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [14]:
df=pd.read_csv("Telco-Customer-Churn.csv")
df

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

In [22]:
df['Contract'].value_counts()

Month-to-month    3875
Two year          1695
One year          1473
Name: Contract, dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customerID          7043 non-null object
gender              7043 non-null object
SeniorCitizen       7043 non-null int64
Partner             7043 non-null object
Dependents          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
MultipleLines       7043 non-null object
InternetService     7043 non-null object
OnlineSecurity      7043 non-null object
OnlineBackup        7043 non-null object
DeviceProtection    7043 non-null object
TechSupport         7043 non-null object
StreamingTV         7043 non-null object
StreamingMovies     7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null float64
TotalCharges        7043 non-null object
Churn               7043 non-null object
dtypes: float64(1), int64(2), obj

In [46]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')

In [5]:
df.dropna(inplace=True)


In [6]:
for i in ['gender','Partner','Dependents','PhoneService','MultipleLines','OnlineBackup','InternetService','OnlineSecurity','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod','Churn']:
    dummy=pd.get_dummies(df[i],drop_first=True,prefix=i) 
    df=pd.concat([df,dummy],axis=1)
    


In [7]:
df

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     StreamingTV_Yes StreamingMovies_No internet service StreamingMovies_Yes  \
0                  0                                   0                   0   
1                  0                                   0                   0   
2                  0                                   0                   0   
3                  0                                   0                   0   
4                  0                                   0                   0   
...              ...                                 ...                 ...   
7038               1                                   0                   1   
7039               1                                   0                   1   
7040               0                                   0                   0   
7041               0                                   0                   0   
7042               1                                   0                   1   

     Contract_One year Contract_Two year PaperlessBilling_Yes  \
0                    0                 0                    1   
1                    1                 0                    0   
2                    0                 0                    1   
3                    1                 0                    0   
4                    0                 0                    1   
...                ...               ...                  ...   
7038                 1                 0                    1   
7039                 1                 0                    1   
7040                 0                 0                    1   
7041                 0                 0                    1   
7042                 0                 1                    1   

     PaymentMethod_Credit card (automatic) PaymentMethod_Electronic check  \
0                                        0                              1   
1                                        0                              0   
2                                        0                              0   
3                                        0                              0   
4                                        0                              1   
...                                    ...                  

In [8]:
df.drop(columns=['customerID','gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineBackup','OnlineSecurity','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod','Churn'],inplace=True)

In [9]:
df

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  gender_Male  \
0                 0       1           29.85         29.85            0   
1                 0      34           56.95       1889.50            1   
2                 0       2           53.85        108.15            1   
3                 0      45           42.30       1840.75            1   
4                 0       2           70.70        151.65            0   
...             ...     ...             ...           ...          ...   
7038              0      24           84.80       1990.50            1   
7039              0      72          103.20       7362.90            0   
7040              0      11           29.60        346.45            0   
7041              1       4           74.40        306.60            1   
7042              0      66          105.65       6844.50            1   

      Partner_Yes  Dependents_Yes  PhoneService_Yes  \
0               1               0                 0   
1               0               0                 1   
2               0               0                 1   
3               0               0                 0   
4               0               0                 1   
...           ...             ...               ...   
7038            1               1                 1   
7039            1               1                 1   
7040            1               1                 0   
7041            1               0                 1   
7042            0               0                 1   

      MultipleLines_No phone service  MultipleLines_Yes  ...  StreamingTV_Yes  \
0                                  1                  0  ...                0   
1                                  0                  0  ...                0   
2                                  0                  0  ...                0   
3                                  1                  0  ...                0   
4                                  0                  0  ...                0   
...                              ...                ...  ...              ...   
7038                               0                  1  ...                1   
7039                               0                  1  ...                1   
7040                               1                  0  ...                0   
7041                               0                  1  ...                0   
7042                               0                  0  ...                1   

      StreamingMovies_No internet service  StreamingMovies_Yes  \
0                                       0                    0   
1                                       0                    0   
2                                       0                    0   
3                                       0                    0   
4                                       0                    0   
...                                   ...                  ...   
7038                                    0                    1   
7039                                    0                    1   
7040                                    0                    0   
7041                                    0                    0   
7042                                    0                    1   

      Contract_One year  Contract_Two year  PaperlessBilling_Yes  \
0                     0                  0                     1   
1                     1                  0                     0   
2                     0                  0                     1   
3                     1                  0                     0   
4                     0                  0                     1   
...                 ...                ...                   ...   
7038                  1                  0                     1   
7039                  1                  0                     1   
7040                  0                  0                     1   
7041      

In [57]:
df.shape

(7032, 31)

In [10]:
X=df.iloc[:,0:30]
Y=df['Churn_Yes']

In [11]:
X.isnull().sum()

SeniorCitizen                            0
tenure                                   0
MonthlyCharges                           0
TotalCharges                             0
gender_Male                              0
Partner_Yes                              0
Dependents_Yes                           0
PhoneService_Yes                         0
MultipleLines_No phone service           0
MultipleLines_Yes                        0
OnlineBackup_No internet service         0
OnlineBackup_Yes                         0
InternetService_Fiber optic              0
InternetService_No                       0
OnlineSecurity_No internet service       0
OnlineSecurity_Yes                       0
DeviceProtection_No internet service     0
DeviceProtection_Yes                     0
TechSupport_No internet service          0
TechSupport_Yes                          0
StreamingTV_No internet service          0
StreamingTV_Yes                          0
StreamingMovies_No internet service      0
StreamingMo

In [12]:
X.columns

Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [60]:
from sklearn.ensemble import ExtraTreesClassifier
import matplotlib.pyplot as plt
model=ExtraTreesClassifier()
model.fit(X,Y)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
                     max_depth=None, max_features='auto', max_leaf_nodes=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
                     oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [66]:
plt.figure(figsize=(12,8))
feat_importances=pd.Series(model.feature_importances_,index=X.columns)
feat_importances.nlargest(31)

TotalCharges                             0.159542
tenure                                   0.151490
MonthlyCharges                           0.135636
InternetService_Fiber optic              0.064307
PaymentMethod_Electronic check           0.038625
gender_Male                              0.037277
PaperlessBilling_Yes                     0.031883
Contract_Two year                        0.030587
Partner_Yes                              0.029460
TechSupport_Yes                          0.028289
Contract_One year                        0.027909
SeniorCitizen                            0.026586
OnlineSecurity_Yes                       0.026022
OnlineBackup_Yes                         0.025910
MultipleLines_Yes                        0.025623
DeviceProtection_Yes                     0.025382
StreamingTV_Yes                          0.023341
Dependents_Yes                           0.022506
StreamingMovies_Yes                      0.021911
PaymentMethod_Credit card (automatic)    0.017857


<Figure size 864x576 with 0 Axes>

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [69]:
from sklearn.metrics import confusion_matrix,accuracy_score,roc_auc_score,roc_curve,classification_report

In [71]:
from sklearn.ensemble import AdaBoostClassifier
ada=AdaBoostClassifier(random_state=1)

In [72]:
ada.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=1)

In [73]:
y_train_prob=ada.predict_proba(X_train)[:,1]
y_train_pred=ada.predict(X_train)

In [74]:
accuracy_score(y_train,y_train_pred)

0.8126777732629012

In [75]:
confusion_matrix(y_train,y_train_pred)

array([[3275,  333],
       [ 589,  725]], dtype=int64)

In [76]:
roc_auc_score(y_train,y_train_prob)

0.8594369606522964

In [77]:
y_test_prob=ada.predict_proba(X_test)[:,1]
y_test_pred=ada.predict(X_test)

In [78]:
accuracy_score(y_test,y_test_pred)

0.8033175355450237

In [79]:
confusion_matrix(y_test,y_test_pred)

array([[1400,  155],
       [ 260,  295]], dtype=int64)

In [80]:
roc_auc_score(y_test,y_test_prob)

0.846244894412097

In [83]:
import lightgbm as lgb
lgb=lightgbm(random_state=1)

NameError: name 'lightgbm' is not defined

In [84]:
lgbc=lgb.LGBMClassifier()

In [85]:
lgbc.fit(X_train,y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [86]:
y_train_prob=lgbc.predict_proba(X_train)[:,1]
y_train_pred=lgbc.predict(X_train)

In [87]:
accuracy_score(y_train,y_train_pred)

0.8870377895164567

In [89]:
confusion_matrix(y_train,y_train_pred)

array([[3423,  185],
       [ 371,  943]], dtype=int64)

In [92]:
roc_auc_score(y_train,y_train_prob)

0.9586048000890969

In [93]:
y_test_prob=lgbc.predict_proba(X_test)[:,1]
y_test_pred=lgbc.predict(X_test)

In [94]:
accuracy_score(y_test,y_test_pred)

0.7829383886255924

In [95]:
confusion_matrix(y_test,y_test_pred)

array([[1376,  179],
       [ 279,  276]], dtype=int64)

In [101]:
roc_auc_score(y_test,y_test_prob)

0.8329822426928536

In [116]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint as sp_randint
from scipy.stats import uniform as sp_uniform
params={'n_estimators':sp_randint(50,200),
       'num_leaves':sp_randint(10,50),
       'max_depth':sp_randint(2,15),
       'learning_rate':sp_uniform(0,1),
       'min_child_samples':sp_randint(2,50)}
rsearch=RandomizedSearchCV(lgbc,param_distributions=params,cv=3,scoring='accuracy',n_jobs=-1,random_state=1,n_iter=100)
rsearch.fit(X,Y)

RandomizedSearchCV(cv=3, error_score='raise-deprecating',
                   estimator=LGBMClassifier(boosting_type='gbdt',
                                            class_weight=None,
                                            colsample_bytree=1.0,
                                            importance_type='split',
                                            learning_rate=0.10213523253819301,
                                            max_depth=3, min_child_samples=49,
                                            min_child_weight=0.001,
                                            min_split_gain=0.0, n_estimators=95,
                                            n_jobs=-1, num_leaves=33,
                                            objective=None, random_state=1,
                                            reg_al...
                                        'min_child_samples': <scipy.stats._distn_infrastructure.rv_frozen object at 0x000001880CED4608>,
                                  

In [117]:
rsearch.best_params_

{'learning_rate': 0.027387593197926163,
 'max_depth': 4,
 'min_child_samples': 6,
 'n_estimators': 146,
 'num_leaves': 32}

In [118]:
lgbc=lgb.LGBMClassifier(**rsearch.best_params_,random_state=1)
lgbc.fit(X_train,y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.027387593197926163,
               max_depth=4, min_child_samples=6, min_child_weight=0.001,
               min_split_gain=0.0, n_estimators=146, n_jobs=-1, num_leaves=32,
               objective=None, random_state=1, reg_alpha=0.0, reg_lambda=0.0,
               silent=True, subsample=1.0, subsample_for_bin=200000,
               subsample_freq=0)

In [119]:
y_train_prob=lgbc.predict_proba(X_train)[:,1]
y_train_pred=lgbc.predict(X_train)

In [120]:
accuracy_score(y_train,y_train_pred)

0.8240552620885819

In [121]:
confusion_matrix(y_train,y_train_pred)

array([[3311,  297],
       [ 569,  745]], dtype=int64)

In [122]:
roc_auc_score(y_train,y_train_prob)

0.8752194725403045

In [123]:
y_test_prob=lgbc.predict_proba(X_test)[:,1]
y_test_pred=lgbc.predict(X_test)

In [124]:
accuracy_score(y_test,y_test_pred)

0.7990521327014218

In [125]:
confusion_matrix(y_test,y_test_pred)

array([[1406,  149],
       [ 275,  280]], dtype=int64)

In [126]:
roc_auc_score(y_test,y_test_prob)

0.8499116479823875

In [136]:
import pickle

file=open('churn.pkl','wb')
pickle.dump(lgbc,file)

In [137]:
model2=open('churn.pkl','rb')

In [138]:
light=pickle.load(model2)
ypred=light.predict(X_test)